config/routes.rb
Rails.application.routes.draw do

  resources :posts, only: [:index, :show, :new, :create, :destroy]
  devise_for :users

  namespace :admin do
    resources :posts, only: [:index, :show, :destroy]
    resources :users
  end

  root 'posts#index'

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  sketch     :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  role                   :string
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  def admin?
    self.role == "admin"
  end

  def avatar_image_url
    "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(self.email)}?s=24"
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  before_action :authenticate_admin

  def authenticate_admin
    unless user_signed_in? && current_user.admin?
      redirect_to(new_user_session_path, notice: "ログインしてください")
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  before_action :set_post, only: [:show, :destroy]

  layout 'admin/layouts/application'

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to admin_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :sketch, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.includes(:user).order(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    @post.user_id = current_user.id if user_signed_in?

    respond_to do |format|
      if @post.invalid?
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      elsif params[:confirm]
        @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :confirm}
      end
    end
  end

  # DELETE /posts
  def destroy
    if user_signed_in?
      post = current_user.posts.find(params[:id])
      post.destroy
    end

    redirect_to posts_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :sketch, :confirm)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_tag(url)
    image_tag(url, class: "gravatar") if url
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sketchers</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- No header, and the drawer stays open on larger screens (fixed drawer). -->
  <div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer">
    <div class="mdl-layout__drawer admin">
      <span class="mdl-layout-title">管理画面</span>
      <nav class="mdl-navigation">
        <%= link_to('トップページ', root_path, class: "mdl-navigation__link") %>
        <%= link_to('絵を描く', new_post_path, class: "mdl-navigation__link") %>
        <%= link_to_if(user_signed_in?, 'ログアウト', destroy_user_session_path, method: :delete, class: "mdl-navigation__link") do
              link_to('ログイン', new_user_session_path, class: "mdl-navigation__link")
        end %>
      </nav>
    </div>
    <main class="mdl-layout__content">
      <div class="page-content">
        <%= yield %>
      </div>
    </main>
  </div>

</body>
</html>

app/views/admin/posts/index.html.erb
<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--12-col">
    <% if notice %>
      <p id="notice"><%= notice %></p>
    <% end %>
  </div>

  <div class="mdl-cell mdl-cell--12-col">
    <h1>Listing Posts</h1>

    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Sketch</th>
          <th>User</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @posts.each do |post| %>
          <tr>
            <td><%= post.title %></td>
            <td class="image-card"><%= post.sketch.html_safe %></td>
            <td><%= post.user.try(:email) %></td>
            <td><%= link_to 'Show', [:admin, post] %></td>
            <td><%= link_to 'Destroy', [:admin, post], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Sketch:</strong>
  <%= sketchily_show(@post.sketch) %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Sketchers</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- No header, and the drawer stays open on larger screens (fixed drawer). -->
  <div class="mdl-layout mdl-js-layout mdl-layout--fixed-drawer">
    <div class="mdl-layout__drawer">
      <span class="mdl-layout-title"><%= gravatar_tag(current_user.try(:avatar_image_url)) %> Sketchers</span>
      <nav class="mdl-navigation">
        <%= link_to('トップページ', root_path, class: "mdl-navigation__link") %>
        <%= link_to('絵を描く', new_post_path, class: "mdl-navigation__link") %>
        <%= link_to_if(current_user.try(:admin?), '管理ページ', admin_posts_path, class: "mdl-navigation__link"){} %>
        <%= link_to_if(user_signed_in?, 'ログアウト', destroy_user_session_path, method: :delete, class: "mdl-navigation__link") do
              link_to('ログイン', new_user_session_path, class: "mdl-navigation__link")
        end %>
      </nav>
    </div>
    <main class="mdl-layout__content">
      <div class="page-content">
        <%= yield %>
      </div>
    </main>
  </div>

</body>
</html>

app/views/posts/confirm.html.erb
<h1>作品登録</h1>

<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--12-col">
    <div class="medium-card mdl-card mdl-shadow--2dp">
      <div class="medium-card-svg">
        <%= @post.sketch.html_safe %>
      </div>
  </div>

  <div class="mdl-cell mdl-cell--12-col">
    <%= form_for(@post) do |f| %>
      <%= hidden_field_tag(:confirm, value: true) %>
      <%= f.hidden_field(:sketch) %>

      <div class="title-text-field mdl-textfield mdl-js-textfield">
        <%= f.label(:title, class: "mdl-textfield__label") %>
        <%= f.text_field(:title, class: "mdl-textfield__input") %>
      </div>

      <div class="action">
        <%= f.submit(class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored") %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<h1>イラスト一覧</h1>

<div class="mdl-grid">
  <% @posts.each do |post| %>
    <div class="mdl-cell mdl-cell--3-col">
      <%= link_to(post) do %>
        <div class="image-card mdl-card mdl-shadow--2dp">
          <div class="image-card-svg">
            <%= post.sketch.html_safe %>
          </div>
          <div class="mdl-card__title">
            <div class="mdl-card__title-text"><%= gravatar_tag(post.user.try(:avatar_image_url)) %> <%= post.title %></div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>絵を描く</h1>

<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--12-col">
    <%= form_for(@post, html: {class: "canvas"}) do |f| %>
      <div id="canvas"></div>
      <%= f.text_area(:sketch, class: "svg-data") %>
      <%= f.submit(class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored") %>
    <% end %>
  </div>
</div>

<%= javascript_include_tag 'sketch' %>

app/views/posts/show.html.erb
<h1><%= gravatar_tag(@post.user.try(:avatar_image_url)) %> <%= @post.title %></h1>

<div class="mdl-grid">
  <div class="mdl-cell mdl-cell--12-col">
    <div class="big-card mdl-card mdl-shadow--2dp">
      <div class="big-card-svg">
        <%= @post.sketch.html_safe %>
      </div>
      <div class="mdl-card__menu">
        <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
          <i class="material-icons">share</i>
        </button>
        <%= link_to_if(user_signed_in? && @post.user_id == current_user.id, '削除', @post, method: :delete, data: {confirm: "削除してもいいですか？"}) {} %>
      </div>
    </div>
  </div>
</div>